#pbulk parameters below
pbulkParam:
  pbulkMode: 2  #Different mode for building pbulks
  cellCount: 10000  #How many cells should be used to create a bulk sample
  nSamples: 5  #How many different samples should be generated
  propVar: 30 #Variances inbetween proportions, check vignette (EFFECTIVE IN MODE 2 ONLY)
  sampleCT: 1 #Sampling for cell types allowed or not (1 or 0) (EFFECTIVE IN MODE 2 ONLY)
