#Input file name - to be implemented fully later on

sampleName: 'Hrvatin_afteint'   #Enter the part BEFORE file extension (ex. 'data.h5ad' should be entered as 'data')
seededRun: 0 #Use if you want this run of the pipeline to be reproducible

cores:
  pbulks: 32
  c_gen: 32
  CDSeq: 16


#pbulk parameters below
pbulkParam:
  pbulkMode: 2  #Different mode for building pbulks
  cellCount: 100000  #How many cells should be used to create a bulk sample
  nSamples: 400  #How many different samples should be generated
  propVar: 40 #Variances inbetween proportions, check vignette (EFFECTIVE IN MODE 2 ONLY, enter negative value to switch to min max prop mode)
  sampleCT: 1 #Sampling for cell types allowed or not (1 or 0) (DEPRECATED)




#Available tests in Seurat:
#   "wilcox"
#   "bimod"
#   "roc"
#   "t"
#   "negbinom"
#   "poisson"
#   "LR"
#   "MAST"
#   "DESeq2"

#Normalizations available in Seurat:
#   LogNormalize
#   CLR #Not working
#   RC
refgenDgeParam:
    test_1: 'bimod'
    test_2: 'wilcox'
    seuratNorm: 'LogNormalize'


#params for scale_transform

#Transform
#   none
#   log
#   sqrt
#   vst (requires high memory)


#scaleC
#   none
#   column
#   row
#   mean
#   column_z-score
#   global_z-score
#   column_min-max
#   global_min-max
#   LogNormalize
#   QN
#   TMM
#   SCTransform (sc-specific)
#   scater (sc-specific)
#   scran (sc-specific)
#   Linnorm (sc-specific)

#scaleT
#   none
#   column
#   row
#   mean
#   column_z-score
#   global_z-score
#   column_min-max
#   global_min-max
#   LogNormalize
#   QN
#   TMM
#   UQ
#   median_ratios

stParam:
  scaleC: SCTransform
  scaleT: TMM
  transform: sqrt
  scaleFirst: 0 #1 = scale first, 0 = transform first


#Unsupervised params:
unsupervisedParams:
  expectedTypes: 9  #Unsupervised expected cell type count

#Marker selection params
markerParams:
  topN: 4   #How many top markers to select
